name: 'Build action'
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - run: git add .
      - run: git config user.name $GITHUB_ACTOR
      - run: git commit -m 'Commit build result'
      - run: git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@gihub.com/GITHUB_REPOSITORY